import { docsClassLayers, ui } from "../l1";

const docsScrollbarClass = [
  docsClassLayers.scrollbar.l1,
  docsClassLayers.scrollbar.l2,
  docsClassLayers.scrollbar.l3,
].join(" ");

const docsHtmlClass = [
  "scroll-smooth",
  "bg-amber-50",
  "text-neutral-950",
  "dark:bg-neutral-950",
  "dark:text-neutral-50",
  docsScrollbarClass,
  "motion-reduce:scroll-auto",
].join(" ");

const docsBodyClass = [
  "min-w-80",
  "bg-amber-50",
  "font-sans",
  "text-sm",
  "leading-[1.65]",
  "text-neutral-950",
  "selection:bg-amber-400/20",
  "selection:text-neutral-950",
  "dark:bg-neutral-950",
  "dark:text-neutral-50",
  "dark:selection:bg-yellow-300/20",
  "dark:selection:text-neutral-50",
  docsScrollbarClass,
].join(" ");

const themeBootScript = `<script>
      (() => {
        try {
          const key = 'carbide.theme';
          const stored = window.localStorage.getItem(key);
          const mode = ['light', 'dark', 'system'].includes(stored) ? stored : 'system';
          const prefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
          const resolved = mode === 'dark' || (mode === 'system' && prefersDark) ? 'dark' : 'light';
          document.documentElement.dataset.theme = resolved;
          document.documentElement.dataset.themeMode = mode;
          document.documentElement.style.colorScheme = resolved;
        } catch {
          document.documentElement.dataset.theme = 'light';
          document.documentElement.dataset.themeMode = 'system';
        }
      })();
    </script>`;

export const docsStaticClassMap: Record<string, string> = {
  "skip-link": [
    "absolute",
    "left-2.5",
    "top-2.5",
    "z-40",
    "-translate-y-[140%]",
    "rounded-md",
    "border",
    ui.borderStrong,
    ui.surface,
    "px-2.5",
    "py-2",
    "font-bold",
    ui.text,
    "focus:translate-y-0",
  ].join(" "),
  "docs-topbar": [
    "sticky",
    "top-0",
    "z-30",
    "min-h-16",
    "border-b",
    ui.border,
    "bg-amber-50/95",
    "dark:bg-neutral-950/92",
    "backdrop-blur",
  ].join(" "),
  "topbar-inner": [
    "mx-auto",
    "flex",
    "min-h-16",
    "w-full",
    "max-w-[1440px]",
    "items-center",
    "gap-[18px]",
    "px-8",
    "max-[860px]:flex-wrap",
    "max-[860px]:gap-2.5",
    "max-[860px]:px-5",
    "max-[560px]:px-4",
  ].join(" "),
  brand: [
    "inline-flex",
    "min-w-max",
    "items-center",
    "gap-2.5",
    ui.text,
    "no-underline",
  ].join(" "),
  "brand-mark": [
    "grid",
    "size-[30px]",
    "place-items-center",
    "rounded-[7px]",
    "border",
    "border-amber-950/70",
    "bg-yellow-400",
    "text-[0.82rem]",
    "font-extrabold",
    "text-neutral-950",
    "shadow-[0_0_20px_rgb(250_204_21_/_0.18)]",
    "dark:border-yellow-200/70",
    "dark:bg-yellow-300",
    "dark:text-black",
    "dark:shadow-black/70",
  ].join(" "),
  "brand-copy": "grid gap-px",
  "brand-name": "text-[0.96rem] font-extrabold leading-[1.1]",
  "brand-label": "text-[0.76rem] leading-[1.1] text-neutral-600 dark:text-neutral-500 max-[560px]:hidden",
  "search-box": [
    "ml-auto",
    "flex",
    "w-[min(420px,34vw)]",
    "items-center",
    "justify-between",
    "gap-4",
    "rounded-lg",
    "border",
    ui.border,
    ui.surfaceSoft,
    "px-3",
    "py-2",
    "text-[0.86rem]",
    ui.muted,
    "max-[860px]:order-3",
    "max-[860px]:ml-0",
    "max-[860px]:w-full",
    "[&_kbd]:min-w-6",
    "[&_kbd]:rounded",
    "[&_kbd]:border",
    "[&_kbd]:border-amber-400/45",
    "dark:[&_kbd]:border-yellow-300/20",
    "[&_kbd]:bg-amber-50",
    "dark:[&_kbd]:bg-black",
    "[&_kbd]:px-1.5",
    "[&_kbd]:py-px",
    "[&_kbd]:text-center",
    "[&_kbd]:font-mono",
    "[&_kbd]:text-[0.72rem]",
    "[&_kbd]:text-amber-950",
    "dark:[&_kbd]:text-yellow-300",
  ].join(" "),
  "topbar-actions": [
    "flex",
    "items-center",
    "gap-2.5",
    "whitespace-nowrap",
    "text-[0.86rem]",
    ui.muted,
    "max-[860px]:ml-auto",
  ].join(" "),
  "version-pill": [
    "rounded-lg",
    "border",
    ui.border,
    ui.surfaceSoft,
    "px-2.5",
    "py-[7px]",
    "text-amber-950 dark:text-yellow-300",
  ].join(" "),
  "github-link": [
    "rounded-lg",
    "border",
    ui.border,
    ui.surfaceSoft,
    "px-2.5",
    "py-[7px]",
    ui.muted,
    "no-underline",
    "hover:text-amber-950",
    "dark:hover:text-yellow-300",
    "max-[560px]:hidden",
  ].join(" "),
  "docs-layout": [
    "mx-auto",
    "grid",
    "w-full",
    "max-w-[1440px]",
    "grid-cols-[270px_minmax(0,760px)_224px]",
    "gap-11",
    "px-8",
    "pb-22",
    "pt-[34px]",
    "max-[1180px]:grid-cols-[minmax(220px,0.32fr)_minmax(0,1fr)]",
    "max-[860px]:grid-cols-1",
    "max-[860px]:gap-7",
    "max-[860px]:px-5",
    "max-[860px]:pb-16",
    "max-[860px]:pt-6",
    "max-[560px]:px-4",
  ].join(" "),
  "docs-sidebar": [
    "sticky",
    "top-[calc(4rem+24px)]",
    "max-h-[calc(100svh-4rem-48px)]",
    "self-start",
    "overflow-auto",
    docsScrollbarClass,
    "border-r",
    ui.border,
    "pr-[22px]",
    "max-[860px]:static",
    "max-[860px]:order-2",
    "max-[860px]:max-h-none",
    "max-[860px]:overflow-visible",
    "max-[860px]:border-r-0",
    "max-[860px]:border-b",
    "max-[860px]:pb-6",
    "max-[860px]:pr-0",
  ].join(" "),
  "sidebar-nav": "grid max-[860px]:grid-cols-2 max-[860px]:gap-[22px] max-[560px]:grid-cols-1",
  "nav-group": "mt-7 first:mt-0 max-[860px]:mt-0",
  "nav-title": "mb-2.5 text-xs font-extrabold uppercase tracking-normal text-amber-700 dark:text-yellow-400",
  "nav-list": "m-0 grid list-none gap-0.5 p-0",
  "nav-link": [
    "block",
    "rounded-md",
    "px-2",
    "py-1",
    "text-[0.9rem]",
    "text-neutral-700",
    "dark:text-neutral-300",
    "no-underline",
    "hover:bg-amber-400/14",
    "hover:text-amber-950",
    "dark:hover:bg-yellow-300/10",
    "dark:hover:text-yellow-300",
    "aria-[current=page]:bg-amber-400/16",
    "aria-[current=page]:text-amber-950",
    "dark:aria-[current=page]:bg-yellow-300/10",
    "dark:aria-[current=page]:text-yellow-300",
  ].join(" "),
  "docs-toc": [
    "sticky",
    "top-[calc(4rem+24px)]",
    "max-h-[calc(100svh-4rem-48px)]",
    "self-start",
    "overflow-auto",
    docsScrollbarClass,
    "border-l",
    ui.border,
    "pl-5",
    "max-[1180px]:hidden",
  ].join(" "),
  "toc-title": "mb-2.5 text-xs font-extrabold uppercase tracking-normal text-amber-700 dark:text-yellow-400",
  "toc-list": "m-0 grid list-none gap-0.5 p-0",
  "toc-link": "block py-1 text-[0.82rem] text-neutral-700 no-underline hover:text-amber-950 dark:text-neutral-300 dark:hover:text-yellow-300",
  "docs-content": [
    "min-w-0",
    "[&_a]:decoration-amber-500/60",
    "[&_a]:underline-offset-[3px]",
    "[&_a:hover]:text-amber-950",
    "dark:[&_a:hover]:text-yellow-300",
    "[&_code]:rounded-md",
    "[&_code]:border",
    "[&_code]:border-amber-300/45",
    "dark:[&_code]:border-yellow-300/16",
    "[&_code]:bg-amber-100/75",
    "dark:[&_code]:bg-black",
    "[&_code]:px-1.5",
    "[&_code]:py-0.5",
    "[&_code]:font-mono",
    "[&_code]:text-[0.88em]",
    "[&_code]:text-amber-950",
    "dark:[&_code]:text-yellow-200",
    "[&_h1]:m-0",
    "[&_h1]:max-w-[780px]",
    "[&_h1]:text-[clamp(2.35rem,5vw,4.75rem)]",
    "[&_h1]:leading-[0.98]",
    "[&_h1]:tracking-normal",
    "[&_h1]:text-neutral-950",
    "dark:[&_h1]:text-neutral-50",
    "max-[860px]:[&_h1]:text-[clamp(2.1rem,12vw,3.5rem)]",
    "[&_h2]:mb-3.5",
    "[&_h2]:mt-0",
    "[&_h2]:text-[1.45rem]",
    "[&_h2]:leading-tight",
    "[&_h2]:tracking-normal",
    "[&_h2]:text-neutral-950",
    "dark:[&_h2]:text-neutral-50",
    "[&_h3]:mb-2.5",
    "[&_h3]:mt-6",
    "[&_h3]:text-[0.98rem]",
    "[&_h3]:leading-snug",
    "[&_h3]:tracking-normal",
    "[&_h3]:text-neutral-950",
    "dark:[&_h3]:text-neutral-50",
    "[&_li+li]:mt-[7px]",
    "[&_ol]:m-0",
    "[&_ol]:list-decimal",
    "[&_ol]:pl-5",
    "[&_p]:mb-3.5",
    "[&_p]:text-neutral-700",
    "dark:[&_p]:text-neutral-300",
    "[&_pre]:mt-[18px]",
    "[&_pre]:overflow-x-auto",
    "[&_pre]:[scrollbar-width:thin]",
    "[&_pre]:[scrollbar-color:rgb(217_119_6)_transparent]",
    "dark:[&_pre]:[scrollbar-color:rgb(250_204_21)_transparent]",
    "[&_pre]:rounded-lg",
    "[&_pre]:border",
    "[&_pre]:border-amber-300/45",
    "dark:[&_pre]:border-yellow-300/16",
    "[&_pre]:bg-amber-100/65",
    "dark:[&_pre]:bg-black",
    "[&_pre]:p-[18px]",
    "[&_pre]:font-mono",
    "[&_pre]:text-[0.86rem]",
    "[&_pre]:leading-[1.65]",
    "[&_pre]:text-amber-950",
    "dark:[&_pre]:text-yellow-200",
    "[&_pre+ol]:mt-[18px]",
    "[&_pre+p]:mt-[18px]",
    "[&_pre+ul]:mt-[18px]",
    "[&_pre_code]:border-0",
    "[&_pre_code]:bg-transparent",
    "[&_pre_code]:p-0",
    "[&_pre_code]:text-[inherit]",
    "[&_pre_code]:text-inherit",
    "[&_section]:scroll-mt-[calc(4rem+24px)]",
    "[&_section]:border-b",
    "[&_section]:border-amber-300/35",
    "dark:[&_section]:border-yellow-300/15",
    "[&_section]:py-[30px]",
    "[&_section:last-child]:border-b-0",
    "[&_ul]:m-0",
    "[&_ul]:list-disc",
    "[&_ul]:pl-5",
  ].join(" "),
  breadcrumb: [
    "mb-4",
    "flex",
    "items-center",
    "gap-2",
    "text-[0.82rem]",
    ui.muted,
    "[&>span+span:before]:mr-2",
    "[&>span+span:before]:text-amber-400/60",
    "dark:[&>span+span:before]:text-yellow-300/35",
    "[&>span+span:before]:content-['/']",
  ].join(" "),
  "article-header": "border-b border-amber-300/35 pb-7 dark:border-yellow-300/15",
  lead: "mt-11 max-w-[720px] text-base leading-[1.7] text-neutral-700 dark:text-neutral-300 [&+&]:mt-2.5 max-[860px]:mt-[34px] max-[860px]:[&+&]:mt-2.5",
  callout: [
    "mt-[18px]",
    "rounded-lg",
    "border",
    ui.border,
    "border-l-[3px]",
    "border-l-amber-700",
    "bg-amber-100/60",
    "dark:border-l-yellow-300",
    "dark:bg-neutral-900/72",
    "px-4",
    "py-3.5",
    "[&_p]:m-0",
  ].join(" "),
  "runtime-map": "mt-5 grid grid-cols-4 gap-2.5 max-[860px]:grid-cols-1",
  "runtime-node": [
    "min-h-[92px]",
    "rounded-lg",
    "border",
    ui.border,
    ui.surfaceSoft,
    "p-3.5",
    "[&_span]:block",
    "[&_span]:text-[0.8rem]",
    "[&_span]:leading-[1.45]",
    "[&_span]:text-neutral-700",
    "dark:[&_span]:text-neutral-400",
    "[&_strong]:mb-[7px]",
    "[&_strong]:block",
    "[&_strong]:text-[0.86rem]",
    "[&_strong]:text-neutral-950",
    "dark:[&_strong]:text-neutral-50",
  ].join(" "),
  "docs-footer": "border-t border-amber-300/35 px-8 py-6 text-[0.84rem] text-neutral-700 dark:border-yellow-300/15 dark:text-neutral-400 max-[560px]:px-4",
  "footer-inner": "mx-auto w-full max-w-[1440px]",
};

export const docsChromeClassLayers = {
  topbar: {
    l1: "sticky top-0 z-30 flex items-center",
    l2: "min-h-16 border-b px-5",
    l3: `${ui.border} bg-amber-50/95 text-neutral-950 backdrop-blur dark:bg-neutral-950/92 dark:text-neutral-50`,
  },
  sidebar: {
    l1: "sticky top-16 self-start",
    l2: "max-h-[calc(100vh-4rem)] border-r px-5 py-6",
    l3: `${ui.border} ${ui.muted}`,
  },
  content: {
    l1: "min-w-0",
    l2: "px-5 py-8",
    l3: docsClassLayers.page.l3,
  },
};

interface DocsStaticHeadersOptions {
  cache: string;
  contract: string;
  type: string;
}

export function docsStaticHeaders({ cache, type, contract }: DocsStaticHeadersOptions): Record<string, string> {
  return {
    "cache-control": cache,
    "content-type": type,
    "x-carbide-component-contract": contract,
  };
}

export function rewriteDocsClasses(html: string): string {
  return addDocumentClasses(html).replace(/class="([^"]*)"/g, (_match: string, classValue: string) => {
    const classes = classValue
      .split(/\s+/)
      .filter(Boolean)
      .flatMap((name: string) => (docsStaticClassMap[name] || name).split(/\s+/));

    return `class="${dedupeClasses(classes).join(" ")}"`;
  });
}

function addDocumentClasses(html: string): string {
  return html
    .replace("<html lang=\"en\">", `<html lang="en" class="${docsHtmlClass}">`)
    .replace("</head>", `    ${themeBootScript}\n  </head>`)
    .replace("<body>", `<body class="${docsBodyClass}">`);
}

function dedupeClasses(classes: string[]): string[] {
  return [...new Set(classes)];
}
