export const ui = {
  accent: 'text-carbide-action',
  action: 'bg-carbide-action text-white hover:bg-carbide-action-hover focus-visible:ring-4 focus-visible:ring-carbide-focus',
  border: 'border-carbide-border',
  borderStrong: 'border-carbide-border-strong',
  code: 'bg-carbide-action-soft text-carbide-action-strong',
  dangerAction: 'bg-carbide-danger text-white hover:bg-carbide-danger-hover focus-visible:ring-4 focus-visible:ring-carbide-focus',
  dangerBadge: 'bg-carbide-danger-soft text-carbide-danger-text',
  divider: 'bg-carbide-border',
  errorSurface: 'bg-carbide-danger-soft',
  errorText: 'text-carbide-danger-text',
  focus: 'focus-visible:ring-4 focus-visible:ring-carbide-focus',
  ghostAction: 'bg-transparent text-carbide-action hover:bg-carbide-action-soft focus-visible:ring-4 focus-visible:ring-carbide-focus',
  goodBadge: 'bg-carbide-success-soft text-carbide-success-text',
  gridLines: 'bg-carbide-border',
  hero: 'bg-gradient-to-br from-carbide-action via-carbide-hero-via to-carbide-text text-white',
  heroMuted: 'text-white/80',
  input: 'bg-white border-carbide-border-strong text-carbide-text focus:border-carbide-action focus:ring-4 focus:ring-carbide-focus',
  muted: 'text-carbide-muted',
  neutralBadge: 'bg-carbide-neutral-soft text-carbide-neutral-text',
  page: 'bg-carbide-page text-carbide-text font-sans',
  secondaryAction: 'bg-white border-carbide-border text-carbide-text hover:border-carbide-border-strong focus-visible:ring-4 focus-visible:ring-carbide-focus',
  selection: 'bg-white border-carbide-border text-carbide-text',
  selectionActive: 'bg-carbide-action-soft border-carbide-action text-carbide-text',
  shadowSubtle: 'shadow-carbide-subtle',
  subtle: 'text-carbide-subtle',
  surface: 'bg-white',
  surfaceQuiet: 'bg-carbide-surface-quiet',
  surfaceSoft: 'bg-carbide-surface-soft',
  text: 'text-carbide-text',
  warnBadge: 'bg-carbide-warning-soft text-carbide-warning-text'
};
